version: "3.6"
services:
  db:
    image: postgres:14-alpine
    privileged: true
    ports:
      - 5432:5432
    volumes:
      - postgresql_data:/var/lib/postgresql
    container_name: appointments-db
    hostname: appointments-db
    networks:
      - network1
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 4000:4000
      - 9568:9568
    volumes:
      - .:/app
      - ./_docker_build:/code/_build
    container_name: appointments-api
    hostname: appointments-api
    environment:
      MIX_ENV: dev
      DATABASE_HOSTNAME: appointments-db
    networks:
      - network1
    depends_on:
      - db

volumes:
  postgresql_data:
    name: postgresql_data


networks:
  network1:
    name: network1